Repository Epitech-Project/My_Marvin, pull requests merged in 2024-03, with the labels that each got.

#18 :twisted_rightwards_arrows: Fix the check files on the CI
  .github/workflows/Mirror.yml
Labels: bug, continuous integration

#15 :hammer: clone repository job
  .env
  .gitignore
  job_dsl.groovy
Labels: enhancement, jobs

#20 :adhesive_bandage: Fix a missunderstanding of the subject
  job_dsl.groovy
Labels: bug, jobs

#21 🚧 Update Jenkins user configuration in my_marvin.yml
  my_marvin.yml
Labels: documentation

#23 :adhesive_bandage: Fix seed jobs bugs
  job_dsl.groovy
Labels: bug, jobs

#24 :twisted_rightwards_arrows: passport control authorization strategy
  my_marvin.yml
Labels: enhancement, configuration
